spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dota_analytics
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

opendota:
  sync:
    enabled: true
    league-ids: 19101
    initial-delay-ms: 5000
    fixed-delay-ms: 600000
    force-reload: false

  rate-limit:
    requests-per-minute: 50
    requests-per-day: 3000
    zone-id: UTC