spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dota_analytics
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

opendota:
  sync:
    enabled: false